const LESSON = {
  title:"我看了一个电影", pinyin:"Wǒ kànle yí ge diànyǐng", en:"I watched a movie",
  level:"HSK 1", duration:"120 phút",
  objectives:[
    {vi:"Hiểu và dùng trợ từ động thái “了 (2)” để diễn tả hành động đã xảy ra hoặc đã hoàn thành.",
     en:"Understand and use the aspect particle 了 (2) for completed actions."},
    {vi:"Nắm vững cách dùng phó từ phạm vi “都”.",
     en:"Master the scope adverb 都."},
    {vi:"Nắm vững cách dùng cơ bản của một số từ ly hợp (离合词).",
     en:"Master the basic use of some separable words."},
    {vi:"Hiểu và biết mô tả tình hình học tập.",
     en:"Understand and describe learning progress."}
  ],
  // ------- TỪ VỰNG (26 từ mới) -------
  words:[
    {id:"w1", han:"上", py:"shàng", pos:"động từ · v.", vi:"lên; lên (xe)", en:"go up; get on; board",
      ex:{han:"你们上火车了吗？", py:"Nǐmen shàng huǒchē le ma?", vi:"Các em lên tàu chưa?", en:"Did you board the train?"}},
    {id:"w2", han:"火车", py:"huǒchē", pos:"danh từ · n.", vi:"tàu hỏa; xe lửa", en:"train",
      ex:{han:"我们上火车了。", py:"Wǒmen shàng huǒchē le.", vi:"Chúng em đã lên tàu.", en:"We boarded the train."}},
    {id:"w3", han:"中午", py:"zhōngwǔ", pos:"danh từ · n.", vi:"buổi trưa", en:"noon",
      ex:{han:"中午车开了。", py:"Zhōngwǔ chē kāi le.", vi:"Buổi trưa xe chạy.", en:"The train departed at noon."}},
    {id:"w4", han:"开", py:"kāi", pos:"động từ · v.", vi:"(xe) khởi hành; chạy", en:"of vehicles: depart; leave",
      ex:{han:"车开了。", py:"Chē kāi le.", vi:"Xe đã chạy.", en:"The train has departed."}},
    {id:"w5", han:"有些", py:"yǒuxiē", pos:"đại từ · pron.", vi:"một số; có những", en:"some; a part of",
      ex:{han:"有些人在看书。", py:"Yǒuxiē rén zài kàn shū.", vi:"Một số người đang đọc sách.", en:"Some people are reading."}},
    {id:"w6", han:"有的", py:"yǒude", pos:"đại từ · pron.", vi:"có cái; một số", en:"some",
      ex:{han:"有的人睡觉了。", py:"Yǒude rén shuìjiào le.", vi:"Có người đã ngủ.", en:"Some people fell asleep."}},
    {id:"w7", han:"了", py:"le", pos:"trợ từ · part.", vi:"trợ từ chỉ hành động đã hoàn thành", en:"indicates completion of an action",
      ex:{han:"我看了一个电影。", py:"Wǒ kànle yí ge diànyǐng.", vi:"Tớ đã xem một bộ phim.", en:"I watched a movie."}},
    {id:"w8", han:"写", py:"xiě", pos:"động từ · v.", vi:"viết", en:"write",
      ex:{han:"我们都会写了。", py:"Wǒmen dōu huì xiě le.", vi:"Chúng em đều biết viết rồi.", en:"We can all write now."}},
    {id:"w9", han:"都", py:"dōu", pos:"phó từ · adv.", vi:"đều; tất cả", en:"all; both",
      ex:{han:"同学们都会说汉语了。", py:"Tóngxuémen dōu huì shuō Hànyǔ le.", vi:"Các bạn đều biết nói tiếng Hán rồi.", en:"The classmates can all speak Chinese now."}},
    {id:"w10", han:"听见", py:"tīngjiàn", pos:"động từ · v.", vi:"nghe thấy", en:"hear",
      ex:{han:"老师，我听不见。", py:"Lǎoshī, wǒ tīng bu jiàn.", vi:"Thưa thầy, em nghe không rõ.", en:"Teacher, I can’t hear you."}},
    {id:"w11", han:"不要", py:"búyào", pos:"phó từ · adv.", vi:"đừng", en:"don’t",
      ex:{han:"请大家不要说话！", py:"Qǐng dàjiā búyào shuōhuà!", vi:"Mọi người đừng nói chuyện!", en:"Everyone, please don’t talk!"}},
    {id:"w12", han:"说话", py:"shuōhuà", pos:"động từ · v.", vi:"nói chuyện", en:"say; speak; talk",
      ex:{han:"请不要说话。", py:"Qǐng búyào shuōhuà.", vi:"Xin đừng nói chuyện.", en:"Please don’t talk."}},
    {id:"w13", han:"听", py:"tīng", pos:"động từ · v.", vi:"nghe", en:"listen to; hear",
      ex:{han:"请听老师的问题。", py:"Qǐng tīng lǎoshī de wèntí.", vi:"Hãy nghe câu hỏi của thầy.", en:"Please listen to the teacher’s question."}},
    {id:"w14", han:"哪些", py:"nǎxiē", pos:"đại từ · pron.", vi:"những … nào", en:"which",
      ex:{han:"你们会写哪些汉字了？", py:"Nǐmen huì xiě nǎxiē Hànzì le?", vi:"Các em biết viết những chữ Hán nào rồi?", en:"Which Chinese characters can you write now?"}},
    {id:"w15", han:"字", py:"zì", pos:"danh từ · n.", vi:"chữ", en:"character; word",
      ex:{han:"我会写这些字了。", py:"Wǒ huì xiě zhèxiē zì le.", vi:"Em biết viết những chữ này rồi.", en:"I can write these characters now."}},
    {id:"w16", han:"明年", py:"míngnián", pos:"danh từ · n.", vi:"năm sau; sang năm", en:"next year",
      ex:{han:"明年女儿上中学。", py:"Míngnián nǚ’ér shàng zhōngxué.", vi:"Sang năm con gái lên trung học.", en:"Next year my daughter will start middle school."}},
    {id:"w17", han:"上", py:"shàng", pos:"động từ · v.", vi:"bắt đầu (học); vào (học)", en:"begin at a fixed time",
      ex:{han:"儿子也上小学了。", py:"Érzi yě shàng xiǎoxué le.", vi:"Con trai cũng vào tiểu học rồi.", en:"My son will also start primary school."}},
    {id:"w18", han:"中学", py:"zhōngxué", pos:"danh từ · n.", vi:"trường trung học", en:"middle school",
      ex:{han:"我们家有了一个中学生。", py:"Wǒmen jiā yǒule yí ge zhōngxuéshēng.", vi:"Nhà mình có một học sinh trung học rồi.", en:"Our family now has a middle school student."}},
    {id:"w19", han:"小学", py:"xiǎoxué", pos:"danh từ · n.", vi:"trường tiểu học", en:"primary school",
      ex:{han:"还有了一个小学生。", py:"Hái yǒule yí ge xiǎoxuéshēng.", vi:"Còn có một học sinh tiểu học nữa.", en:"And a primary school student too."}},
    {id:"w20", han:"中学生", py:"zhōngxuéshēng", pos:"danh từ · n.", vi:"học sinh trung học", en:"middle school student",
      ex:{han:"他是中学生。", py:"Tā shì zhōngxuéshēng.", vi:"Cậu ấy là học sinh trung học.", en:"He is a middle school student."}},
    {id:"w21", han:"小学生", py:"xiǎoxuéshēng", pos:"danh từ · n.", vi:"học sinh tiểu học", en:"primary school student; pupil",
      ex:{han:"她是小学生。", py:"Tā shì xiǎoxuéshēng.", vi:"Cô bé là học sinh tiểu học.", en:"She is a primary school student."}},
    {id:"w22", han:"上学", py:"shàngxué", pos:"động từ · v.", vi:"đi học; nhập học", en:"start school; go to school",
      ex:{han:"上学后，他们都忙了。", py:"Shàngxué hòu, tāmen dōu máng le.", vi:"Sau khi đi học, chúng đều bận.", en:"After starting school, they are both busy."}},
    {id:"w23", han:"他们", py:"tāmen", pos:"đại từ · pron.", vi:"họ; bọn họ", en:"they; them",
      ex:{han:"他们都忙了。", py:"Tāmen dōu máng le.", vi:"Họ đều bận rồi.", en:"They are both busy now."}},
    {id:"w24", han:"她们", py:"tāmen", pos:"đại từ · pron.", vi:"họ (chỉ người nữ)", en:"they; them (female)",
      ex:{han:"她们是学生。", py:"Tāmen shì xuésheng.", vi:"Họ (các bạn nữ) là học sinh.", en:"They (females) are students."}},
    {id:"w25", han:"它们", py:"tāmen", pos:"đại từ · pron.", vi:"chúng (chỉ vật/động vật)", en:"they; them (things/animals)",
      ex:{han:"它们都很好。", py:"Tāmen dōu hěn hǎo.", vi:"Chúng đều rất tốt.", en:"They (things) are all fine."}},
    {id:"w26", han:"晚", py:"wǎn", pos:"tính từ · adj.", vi:"muộn; trễ", en:"late",
      ex:{han:"太晚了，睡觉吧。", py:"Tài wǎn le, shuìjiào ba.", vi:"Muộn quá rồi, đi ngủ thôi.", en:"It’s too late, let’s go to bed."}}
  ],
  // ------- HÁN TỰ (30 chữ) · gif=null => hiển thị placeholder. Dán Base64 Data URI để thêm GIF. -------
  chars:[
    {c:"上", py:"shàng", vi:"lên; trên", en:"up; on", strokes:3, gif:null},
    {c:"火", py:"huǒ", vi:"lửa", en:"fire", strokes:4, gif:null},
    {c:"车", py:"chē", vi:"xe", en:"vehicle", strokes:4, gif:null},
    {c:"中", py:"zhōng", vi:"giữa; trung", en:"middle", strokes:4, gif:null},
    {c:"午", py:"wǔ", vi:"giờ ngọ; trưa", en:"noon", strokes:4, gif:null},
    {c:"开", py:"kāi", vi:"mở; khởi hành", en:"open; start", strokes:4, gif:null},
    {c:"有", py:"yǒu", vi:"có", en:"have", strokes:6, gif:null},
    {c:"些", py:"xiē", vi:"một số", en:"some", strokes:8, gif:null},
    {c:"的", py:"de", vi:"(trợ từ)", en:"(particle)", strokes:8, gif:null},
    {c:"了", py:"le", vi:"(trợ từ hoàn thành)", en:"(aspect particle)", strokes:2, gif:null},
    {c:"写", py:"xiě", vi:"viết", en:"write", strokes:5, gif:null},
    {c:"都", py:"dōu", vi:"đều; tất cả", en:"all; both", strokes:11, gif:null},
    {c:"听", py:"tīng", vi:"nghe", en:"listen", strokes:7, gif:null},
    {c:"见", py:"jiàn", vi:"gặp; thấy", en:"to see", strokes:4, gif:null},
    {c:"不", py:"bù", vi:"không", en:"not; no", strokes:4, gif:null},
    {c:"要", py:"yào", vi:"muốn; cần", en:"want; need", strokes:9, gif:null},
    {c:"说", py:"shuō", vi:"nói", en:"speak", strokes:9, gif:null},
    {c:"话", py:"huà", vi:"lời; chuyện", en:"words; speech", strokes:8, gif:null},
    {c:"哪", py:"nǎ", vi:"nào", en:"which", strokes:9, gif:null},
    {c:"字", py:"zì", vi:"chữ", en:"character", strokes:6, gif:null},
    {c:"明", py:"míng", vi:"sáng; minh", en:"bright", strokes:8, gif:null},
    {c:"年", py:"nián", vi:"năm", en:"year", strokes:6, gif:null},
    {c:"学", py:"xué", vi:"học", en:"to study", strokes:8, gif:null},
    {c:"小", py:"xiǎo", vi:"nhỏ", en:"small", strokes:3, gif:null},
    {c:"生", py:"shēng", vi:"sinh; sống", en:"life; to be born", strokes:5, gif:null},
    {c:"他", py:"tā", vi:"anh ấy; nó", en:"he; him", strokes:5, gif:null},
    {c:"们", py:"men", vi:"(số nhiều)", en:"(plural)", strokes:5, gif:null},
    {c:"她", py:"tā", vi:"cô ấy; chị ấy", en:"she; her", strokes:6, gif:null},
    {c:"它", py:"tā", vi:"nó (vật/động vật)", en:"it", strokes:5, gif:null},
    {c:"晚", py:"wǎn", vi:"muộn; tối", en:"late; evening", strokes:11, gif:null}
  ],
  // ------- NGỮ PHÁP -------
  grammar:{
    point:"Trợ từ động thái 了 (2), phó từ phạm vi 都, và từ ly hợp (离合词)",
    intro:"Bài học có ba điểm ngữ pháp: trợ từ 了 chỉ hành động đã hoàn thành, phó từ 都 chỉ phạm vi “đều/tất cả”, và cách dùng một số từ ly hợp.",
    blocks:[
      {h:"1. 了 (le)(2) — hành động đã hoàn thành",
       body:"“了(2)” đặt sau động từ để chỉ hành động đã xảy ra hoặc đã hoàn thành. Khi phủ định dùng “没” và bỏ “了”.",
       formula:[["V + 了","hành động đã xảy ra / hoàn thành"],
                ["没 + V (bỏ 了)","phủ định: chưa / không (làm gì)"]],
       ex:[{han:"我看了一个电影。",py:"Wǒ kànle yí ge diànyǐng.",vi:"Tôi đã xem một bộ phim."},
           {han:"我昨天没去商店。",py:"Wǒ zuótiān méi qù shāngdiàn.",vi:"Hôm qua tôi không đi cửa hàng."}]},
      {h:"2. 离合词 — Từ ly hợp (1)",
       body:"Các từ như 上课、下课、上班、下班、说话、读书、睡觉、看病、生病 có thể dùng liền hoặc tách ra và chèn thành phần hạn chế vào giữa.",
       formula:[["睡觉 → 睡了觉；睡了一觉","ngủ → đã ngủ; ngủ một giấc"],
                ["上课 → 上了课；上中文课","học → đã học; học tiết tiếng Trung"],
                ["说话 → 说了话；说了很多话","nói → đã nói; nói rất nhiều"]],
       ex:[{han:"我睡了一觉。",py:"Wǒ shuìle yí jiào.",vi:"Tôi đã ngủ một giấc."},
           {han:"他说了很多话。",py:"Tā shuōle hěn duō huà.",vi:"Anh ấy đã nói rất nhiều."}]},
      {h:"3. 都 (dōu) — phó từ phạm vi",
       body:"“都” biểu thị “toàn bộ, tất cả”. Đối tượng được tổng quát đặt TRƯỚC “都”; từ phủ định đặt SAU “都”.",
       formula:[["(đối tượng) + 都 + V","tất cả đều …"],
                ["… + 都 + 没/不 …","đều không / đều chưa …"]],
       ex:[{han:"我们都会写了。",py:"Wǒmen dōu huì xiě le.",vi:"Chúng em đều biết viết rồi."},
           {han:"同学们都没听见。",py:"Tóngxuémen dōu méi tīngjiàn.",vi:"Các bạn đều không nghe thấy."}]}
    ]
  },
  // ------- BÀI ĐỌC (3 đoạn hội thoại) -------
  texts:[
    {title:"Khóa văn 1 — 课文 1", context:"Sau giờ học, trong lớp, Bạch Gia Nguyệt và Trần Thiên Trung nói về chuyến đi lần trước.",
     lines:[
       {sp:"白家月", sppy:"Bái Jiāyuè", han:"你们上火车后看见王老师了吗？", py:"Nǐmen shàng huǒchē hòu kànjiàn Wáng lǎoshī le ma?", vi:"Sau khi lên tàu các bạn có thấy thầy Vương không?"},
       {sp:"陈天中", sppy:"Chén Tiānzhōng", han:"没看见。中午车开后，有些人在看书，有些人睡觉了。", py:"Méi kànjiàn. Zhōngwǔ chē kāi hòu, yǒuxiē rén zài kàn shū, yǒuxiē rén shuìjiào le.", vi:"Không thấy. Sau khi tàu chạy lúc trưa, một số người đọc sách, một số người ngủ."},
       {sp:"白家月", sppy:"Bái Jiāyuè", han:"你呢？", py:"Nǐ ne?", vi:"Còn cậu?"},
       {sp:"陈天中", sppy:"Chén Tiānzhōng", han:"我看了一个电影。", py:"Wǒ kànle yí ge diànyǐng.", vi:"Tớ đã xem một bộ phim."}
     ]},
    {title:"Khóa văn 2 — 课文 2", context:"Trong lớp, thầy Vương Nhất Phi hỏi học sinh về tình hình học tập.",
     lines:[
       {sp:"王一飞", sppy:"Wáng Yīfēi", han:"你们会说汉语了，也会写汉字了吗？", py:"Nǐmen huì shuō Hànyǔ le, yě huì xiě Hànzì le ma?", vi:"Các em đã biết nói tiếng Hán rồi, cũng biết viết chữ Hán chưa?"},
       {sp:"白家月", sppy:"Bái Jiāyuè", han:"我们都会写了。", py:"Wǒmen dōu huì xiě le.", vi:"Chúng em đều biết viết rồi."},
       {sp:"陈天中", sppy:"Chén Tiānzhōng", han:"老师，我听不见。", py:"Lǎoshī, wǒ tīng bu jiàn.", vi:"Thưa thầy, em nghe không rõ."},
       {sp:"王一飞", sppy:"Wáng Yīfēi", han:"请大家不要说话！请听老师的问题：你们都会写哪些汉字了？", py:"Qǐng dàjiā búyào shuōhuà! Qǐng tīng lǎoshī de wèntí: Nǐmen dōu huì xiě nǎxiē Hànzì le?", vi:"Mọi người đừng nói chuyện! Hãy nghe câu hỏi: Các em biết viết những chữ Hán nào rồi?"},
       {sp:"陈天中", sppy:"Chén Tiānzhōng", han:"我会写这些字了，您看！", py:"Wǒ huì xiě zhèxiē zì le, nín kàn!", vi:"Em biết viết những chữ này rồi, thầy xem!"}
     ]},
    {title:"Khóa văn 3 — 课文 3", context:"Ở nhà, Lưu Minh và Vương Nhất Tuyết nói về việc lên lớp của các con.",
     lines:[
       {sp:"刘明", sppy:"Liú Míng", han:"明年女儿上中学。", py:"Míngnián nǚ’ér shàng zhōngxué.", vi:"Sang năm con gái lên trung học."},
       {sp:"王一雪", sppy:"Wáng Yīxuě", han:"对。儿子也上小学了。", py:"Duì. Érzi yě shàng xiǎoxué le.", vi:"Đúng vậy. Con trai cũng vào tiểu học rồi."},
       {sp:"刘明", sppy:"Liú Míng", han:"我们家有了一个中学生。", py:"Wǒmen jiā yǒule yí ge zhōngxuéshēng.", vi:"Nhà mình có một học sinh trung học rồi."},
       {sp:"王一雪", sppy:"Wáng Yīxuě", han:"还有了一个小学生。", py:"Hái yǒule yí ge xiǎoxuéshēng.", vi:"Còn có một học sinh tiểu học nữa."},
       {sp:"刘明", sppy:"Liú Míng", han:"上学后，他们都忙了。", py:"Shàngxué hòu, tāmen dōu máng le.", vi:"Sau khi đi học, chúng đều bận."},
       {sp:"王一雪", sppy:"Wáng Yīxuě", han:"是的。太晚了，睡觉吧。", py:"Shì de. Tài wǎn le, shuìjiào ba.", vi:"Đúng vậy. Muộn quá rồi, đi ngủ thôi."}
     ]}
  ],
  tongue:[
    {han:"四是四，十是十。", py:"Sì shì sì, shí shì shí.", vi:"Bốn là bốn, mười là mười."},
    {han:"十四是十四，四十是四十。", py:"Shísì shì shísì, sìshí shì sìshí.", vi:"Mười bốn là mười bốn, bốn mươi là bốn mươi."}
  ]
};
